spring:
    profiles:
        active:
        - dev
---
server:
   port: 8770
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8770/eureka/
    register-with-eureka: false
#  server:
#    enable-self-preservation: false
spring:
  profiles: dev
  application:
    name: eurekerServers
---
server:
   port: 8771
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8771/eureka/
    register-with-eureka: false
#  server:
#    enable-self-preservation: false
spring:
  profiles: test
  application:
    name: eurekerServers
